# Generated by Django 4.2.5 on 2024-06-17 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sch', '0002_update'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('welcome_address', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='slides/')),
            ],
        ),
    ]
