# Generated by Django 4.2.5 on 2024-06-17 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sch', '0003_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='about/'),
        ),
    ]
