# Generated by Django 4.2.5 on 2024-06-17 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sch', '0004_alter_about_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='slides/'),
        ),
    ]
