# Generated by Django 4.2.5 on 2024-06-17 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sch', '0005_alter_about_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='About',
            new_name='HAbout',
        ),
    ]
