# Generated by Django 4.2.5 on 2024-06-17 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sch', '0008_whyus_alter_habout_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='whyus',
            name='icon',
        ),
    ]
