# Generated by Django 4.2.5 on 2024-06-17 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sch', '0010_teachers_alter_habout_image_alter_hadmission_video_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachers',
            name='full_name',
            field=models.CharField(default='exit', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teachers',
            name='role',
            field=models.CharField(default='exit', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teachers',
            name='t_id',
            field=models.CharField(default='exit', max_length=50),
            preserve_default=False,
        ),
    ]
