# Generated by Django 4.2.5 on 2024-06-17 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sch', '0011_teachers_full_name_teachers_role_teachers_t_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Teachers',
            new_name='Teacher',
        ),
        migrations.RenameModel(
            old_name='Whyus',
            new_name='Whyu',
        ),
    ]
