# Generated by Django 4.2.5 on 2024-06-17 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sch', '0012_rename_teachers_teacher_rename_whyus_whyu'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, null=True, upload_to='uploads/logo/images/')),
            ],
        ),
    ]
