# Generated by Django 4.2.5 on 2024-06-17 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sch', '0014_footer_logo_img2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Footer',
        ),
        migrations.AddField(
            model_name='logo',
            name='address',
            field=models.CharField(default='exit', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='logo',
            name='facebook',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='logo',
            name='instagram',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='logo',
            name='youtube',
            field=models.URLField(blank=True, null=True),
        ),
    ]
