# Generated by Django 4.2.5 on 2024-06-17 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sch', '0015_delete_footer_logo_address_logo_facebook_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='logo',
            name='school_name',
            field=models.CharField(default='exit', max_length=50),
            preserve_default=False,
        ),
    ]
